[package]
name = "x3dh-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = { version = "4.1.1", features = ["rand_core"] }
rand_core = "0.6.4"
rand = "0.8.5"
sha2 = "0.10.8"
hmac = "0.12.1"
hkdf = "0.12.3"

